// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Rj_iYcjWa0HtVxdIFsbXkDxSgxVlwqI',
    appId: '1:269212566408:web:907eb7ae350e7c66b0b03d',
    messagingSenderId: '269212566408',
    projectId: 'emcus-a08cb',
    authDomain: 'emcus-a08cb.firebaseapp.com',
    databaseURL: 'https://emcus-a08cb-default-rtdb.firebaseio.com',
    storageBucket: 'emcus-a08cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsfuFuwkfem3RZsIzBM-hl9whWme1e_9E',
    appId: '1:269212566408:android:cca96eb9ce3b45ccb0b03d',
    messagingSenderId: '269212566408',
    projectId: 'emcus-a08cb',
    databaseURL: 'https://emcus-a08cb-default-rtdb.firebaseio.com',
    storageBucket: 'emcus-a08cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHf-_soWDSqkSGNBqs4miUtwN_9s8_DaI',
    appId: '1:269212566408:ios:032b316369cf0310b0b03d',
    messagingSenderId: '269212566408',
    projectId: 'emcus-a08cb',
    databaseURL: 'https://emcus-a08cb-default-rtdb.firebaseio.com',
    storageBucket: 'emcus-a08cb.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );
}
